# 自動生成：tools/gen_voice_fx.py（元は tools/voice_lines.tsv）。手で書き換えない
class_name VoiceLines

## 字幕（日本語）または鍵 → 音声ファイルの id
const BY_TEXT := {
	"全艦、前進。第七打撃群は中央を進め。": "v01",
	"ヒルカゼ砲手、配置よし。マウスで狙い、左クリックで撃て。": "v02",
	"前方に敵戦列。各艦、砲撃始め。": "v04",
	"ミサイル接近！ 赤い菱形だ。先に落とせ！": "v06",
	"敵戦列へ突入する。右舷、敵巡洋艦！": "v07",
	"攻撃艇は居座って撃ってくる。赤く光ったら急げ。": "v08",
	"砲台を潰せ！ 友軍が撃たれている！": "v09",
	"機雷帯に入る。進路上の機雷だけ撃て。": "v10",
	"橙の印が本艦の進路上だ。全部撃つ必要はない。": "v11",
	"黄の印は護衛艦の進路上。余裕があれば撃て。": "v12",
	"機雷帯を抜けた。全艦、短距離跳躍に入る。": "v13",
	"跳躍先は敵戦艦の真横だ。出たらすぐ撃てるようにしておけ。": "v14",
	"敵戦艦の舷側を抜ける。砲台を片っ端から潰せ！": "v15",
	"敵戦艦の主砲が友軍を狙っている！": "v16",
	"敵戦艦を抜けた。": "v17",
	"敵要塞に高エネルギー反応！ 狙いは左翼艦隊だ！": "v18",
	"砲口の周りの集束器、三基を全部潰せ！": "v19",
	"要塞宙域を離脱する。全艦、跳躍！ 行き先は質量兵器の航路だ！": "v20",
	"質量兵器が防衛ラインへ向かっている！ 推進器を止めろ！": "v21",
	"離脱する！ 砲座、後方へ旋回！": "v22",
	"追撃機多数！ ミサイルも来るぞ！": "v23",
	"こちら友軍本隊。ヒルカゼ、よく戻った。後ろは任せろ。": "v24",
	"作戦終了。全艦、帰投する。": "v25",
	"友軍巡洋艦、被弾……！ 砲台を黙らせろ！": "v26",
	"敵戦艦の主砲、友軍に命中……！": "v27",
	"砲台沈黙！ 左翼艦隊は無事だ。よくやった！": "v28",
	"大型レーザー、左翼艦隊に直撃……！": "v29",
	"副砲の掃射が来る！ 潜るぞ、つかまれ！": "v30",
	"アオバト被弾！ 航行に支障なし！": "v31",
	"推進停止！ シールドが消えた、制御装置を狙え！": "v32",
	"装甲が吹き飛んだ！ 爆破点を撃て！": "v33",
	"質量兵器、崩壊！ 防衛ラインは守られた！": "v34",
	"……防衛ラインの艦隊が、やられた。だが作戦は続行する。離脱しろ！": "v35",
	"前方に敵巡洋艦、跳躍してきた！": "v36",
	"escort_0": "escort_0",
	"escort_1": "escort_1",
	"escort_2": "escort_2",
	"escort_3": "escort_3",
}

## id → 英語のセリフ（字幕の下に小さく出す）
const EN := {
	"v01": "All ships, advance. Seventh Strike Group, take the center.",
	"v02": "Hirukaze gunner, you're on station. Put the reticle on them, and fire.",
	"v04": "Enemy line, dead ahead. All ships, open fire.",
	"v06": "Missiles inbound! Red diamonds. Take them out first!",
	"v07": "We're breaking into their line. Enemy cruiser, starboard side!",
	"v08": "Gunboats will hang around and shoot. When they glow red, hurry.",
	"v09": "Knock out those turrets! Our ships are taking fire!",
	"v10": "Entering the minefield. Only shoot the mines in our path.",
	"v11": "Orange markers are on our course. You don't have to clear them all.",
	"v12": "Yellow markers are in the escorts' path. Hit them if you can.",
	"v13": "We're clear of the minefield. All ships, stand by for jump.",
	"v14": "We'll come out right beside their battleship. Be ready to fire the moment we exit.",
	"v15": "We're running down the battleship's flank. Take out every turret you see!",
	"v16": "Their main guns are targeting our fleet!",
	"v17": "We're past the battleship.",
	"v18": "Massive energy reading from the fortress! It's aimed at our left wing!",
	"v19": "The focusing nodes around the muzzle. Destroy all three!",
	"v20": "We're leaving the fortress. All ships, jump! Destination, the mass weapon's path!",
	"v21": "The mass weapon is heading for our defense line! Stop its thrusters!",
	"v22": "We're pulling out! Turret, swing aft!",
	"v23": "Multiple pursuers! Missiles coming in, too!",
	"v24": "Main fleet here. Welcome back, Hirukaze. We've got your six.",
	"v25": "Operation complete. All ships, return to base.",
	"v26": "Friendly cruiser hit! Silence those turrets!",
	"v27": "Battleship main gun... it hit one of ours!",
	"v28": "The cannon is silent! Our left wing is safe. Good work!",
	"v29": "Direct hit on the left wing... we're losing ships!",
	"v30": "Sweep beam incoming! We're diving. Hold on!",
	"v31": "Aobato is hit! She's still flying!",
	"v32": "Thrusters are down! The shields are gone. Hit the control units!",
	"v33": "The armor's blown open! Hit the core!",
	"v34": "The mass weapon is breaking up! The defense line is safe!",
	"v35": "We've lost the defense line fleet... But the operation goes on. Get out of there!",
	"v36": "Enemy cruiser jumping in, dead ahead!",
	"escort_0": "Escort Aobato is down!",
	"escort_1": "Escort Shirasagi is down!",
	"escort_2": "Escort Kawasemi is down!",
	"escort_3": "Escort Tsubame is down!",
}
